### PR TITLE
added regex form item type

### PR DESCRIPTION
**Pull request by mvnm**

### CODE REVIEW

**Comment by mvnm** [comment]
This implies the regex expression should be passed in the value attribute. 

At the moment the value attribute is used by the hidden types to just bounce data.

Not really the best place to put it, but I wouldn't create an extra field just to hold the regex expression.

What do you think?

**Comment by romeo1m** [comment]
in HTML this will be put on input tag like:

```html
<input pattern="regexp"/>
```

From my POV it would be more clear to let the FormItem type = "regex", but add another attribute: `FormItem.pattern` to be used only when the type is regex.

The downside is that the number of attributes increases.

The upside is that the names are more intuitive (`value` makes me think to user input rather to input constraints - but maybe I'm biased from HTML), and the switch from HTML to programming and vice-versa should be easier when a certain consistency is kept between JSON and HTML attributes.

However, I don't consider this a big issue, so I'm waiting for your opinion and then eventually merge it.

**Comment by mvnm** [comment]
Yea, having an extra attribute `pattern` seems a cleaner way. I've added it on the schema, please update the logic from behind the scenes.

**Comment by romeo1m** [comment]
PLease rebase as you pushed a commit from an accepted PR again.

**Comment by mvnm** [comment]
Done

**Comment by romeo1m** [comment]
This approach is not good after all.

In HTML the type can be anything, while you can declare a pattern. So having type "regex" is wrong because you couldn't declare your desired type.

We have to remove `FormItemType.regex` and just let `FormItemType.pattern` there. I guess the platform has to validate both the type and the pattern (if provided). I will do these changes.

**Pull request merged**
